# Live Code 2
## Introduction
- Name: Izzan Dienurrahman
- Batch: HCK-003

## Objective
- Membuat model inference

## Problem Statements
- Membuat atau meload data inference
- Meload model yang telah di save sebelumnya
- Melakukan inference pada data baru

# Import Library

In [43]:
# import library yang dibutuhkan
import pandas as pd
import numpy  as np
import joblib

## Load Model

In [44]:
# load model, encoder, scaler, dan selected features
with open('model_tree.pkl','rb') as file_1:
    model_tree = joblib.load(file_1)

with open('best_parameter.txt','rb') as file_2:
    best_parameter = joblib.load(file_2)

with open('scaled_num_col.txt','rb') as file_3:
    scaled_num_col = joblib.load(file_3)

with open('encoded_cat_col.txt','rb') as file_4:
    encoded_cat_col = joblib.load(file_4)

In [45]:
best_parameter

{'estimator__criterion': 'gini',
 'estimator__max_depth': 2,
 'estimator__splitter': 'random'}

# Data Loading

## Construct Data Infer

In [46]:
# semua fitur/kolom
features = ['age', 'sex', 'cp', 'thalach', 'exang', 'oldpeak', 'slope', 'ca',
       'thal']

# artificial data infer
age = [39, 40, 28, 50, 40]
sex = ['Male', 'Female', 'Male', 'Female', 'Female']
cp = [2, 0, 2,  0,  2]
thalach = [130,110,120,120,100]
exang = [0,0,1,0,0]
oldpeak = [0. , 2. , 6.2, 1. , 0.8]
slope = ['Upsloping', 'Flat', 'Downsloping', 'Flat', 'Downsloping']
ca = [1,3,2,0,2]
thal = ['Normal', 'Reversible defect', 'Fixed defect','Normal', 'Reversible defect']

D = {
    'age':age,
    'sex':sex,
    'cp':cp, 
    'thalach':thalach, 
    'exang':exang,
    'oldpeak':oldpeak, 
    'slope':slope, 
    'ca':ca, 
    'thal':thal
    }
data_infer = pd.DataFrame(data=D,columns=features)

In [47]:
data_infer.head()

,age,sex,cp,thalach,exang,oldpeak,slope,ca,thal
0,39,Male,2,130,0,0.0,Upsloping,1,Normal
1,40,Female,0,110,0,2.0,Flat,3,Reversible defect
2,28,Male,2,120,1,6.2,Downsloping,2,Fixed defect
3,50,Female,0,120,0,1.0,Flat,0,Normal
4,40,Female,2,100,0,0.8,Downsloping,2,Reversible defect

# Data Inference Preprocessing

## Scaling & Encoding

In [48]:
#Scaling data inference
df_infer_num= data_infer[scaled_num_col].copy()
df_infer_num

   age  thalach
0   39      130
1   40      110
2   28      120
3   50      120
4   40      100

In [49]:
#Encoding data inference
data_infer[encoded_cat_col]

      sex        slope               thal
0    Male    Upsloping             Normal
1  Female         Flat  Reversible defect
2    Male  Downsloping       Fixed defect
3  Female         Flat             Normal
4  Female  Downsloping  Reversible defect

In [50]:
data_infer

,age,sex,cp,thalach,exang,oldpeak,slope,ca,thal
0,39,Male,2,130,0,0.0,Upsloping,1,Normal
1,40,Female,0,110,0,2.0,Flat,3,Reversible defect
2,28,Male,2,120,1,6.2,Downsloping,2,Fixed defect
3,50,Female,0,120,0,1.0,Flat,0,Normal
4,40,Female,2,100,0,0.8,Downsloping,2,Reversible defect

# Inferencing

In [51]:
# predict result
pred = model_tree.predict(data_infer)

In [52]:
# show data infer + prediction
data_infer['pred_target'] = pred
data_infer

,age,sex,cp,thalach,exang,oldpeak,slope,ca,thal,pred_target
0,39,Male,2,130,0,0.0,Upsloping,1,Normal,1
1,40,Female,0,110,0,2.0,Flat,3,Reversible defect,0
2,28,Male,2,120,1,6.2,Downsloping,2,Fixed defect,0
3,50,Female,0,120,0,1.0,Flat,0,Normal,1
4,40,Female,2,100,0,0.8,Downsloping,2,Reversible defect,0